# SPDX-FileCopyrightText: 2026 CERN
# SPDX-License-Identifier: LGPL-3.0-or-later

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG != null
    - if: $CI_COMMIT_BRANCH == "dev"

stages:
  - build
  - test
  - deploy

# Based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
make-gentoo-docker-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  dependencies: []
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      if [[ "$CI_COMMIT_TAG" != "" ]]; then
        export IMAGE_DESTINATION=$CI_REGISTRY/adaptyst/adaptyst:latest
        export IMAGE_DESTINATION_DETAILED=$CI_REGISTRY/adaptyst/adaptyst:$CI_COMMIT_TAG
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION --destination $IMAGE_DESTINATION_DETAILED
        echo "Image pushed successfully to ${IMAGE_DESTINATION} and ${IMAGE_DESTINATION_DETAILED}"
      elif [[ "$CI_PIPELINE_SOURCE" == "web" || "$CI_COMMIT_BRANCH" == "dev" ]]; then
        export IMAGE_DESTINATION=$CI_REGISTRY/adaptyst/adaptyst:$CI_COMMIT_SHORT_SHA
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION
        echo "Image pushed successfully to ${IMAGE_DESTINATION}"
      else
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
        echo "Image built successfully"
      fi

# Based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
make-alma10-docker-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  dependencies: []
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      if [[ "$CI_COMMIT_TAG" != "" ]]; then
        export IMAGE_DESTINATION=$CI_REGISTRY/adaptyst/adaptyst:alma10-latest
        export IMAGE_DESTINATION_DETAILED=$CI_REGISTRY/adaptyst/adaptyst:alma10-$CI_COMMIT_TAG
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-alma --destination $IMAGE_DESTINATION --destination $IMAGE_DESTINATION_DETAILED
        echo "Image pushed successfully to ${IMAGE_DESTINATION} and ${IMAGE_DESTINATION_DETAILED}"
      elif [[ "$CI_PIPELINE_SOURCE" == "web" || "$CI_COMMIT_BRANCH" == "dev" ]]; then
        export IMAGE_DESTINATION=$CI_REGISTRY/adaptyst/adaptyst:alma10-$CI_COMMIT_SHORT_SHA
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-alma --destination $IMAGE_DESTINATION
        echo "Image pushed successfully to ${IMAGE_DESTINATION}"
      else
        /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile-alma --no-push
        echo "Image built successfully"
      fi

make-gentoo-apptainer-image:
  tags:
    - docker-privileged-xl
  image:
    name: gitlab-registry.cern.ch/linuxsupport/alma10-base
  stage: build
  dependencies: []
  before_script:
    - dnf install -y epel-release
    - dnf install -y apptainer xrootd-client
    - echo $KERBEROS_PASSWORD | kinit ${KERBEROS_USER}
  script:
    - apptainer build --build-arg project_dir="$CI_PROJECT_DIR" adaptyst.sif $CI_PROJECT_DIR/apptainer.def
    - |
      if [[ "$CI_COMMIT_TAG" != "" ]]; then
        xrdcp -C auto --rm-bad-cksum -t 5 adaptyst.sif root://eosuser.cern.ch/$WEB_STORAGE/apptainer/adaptyst-$CI_COMMIT_TAG.sif
      elif [[ "$CI_PIPELINE_SOURCE" == "web" || "$CI_COMMIT_BRANCH" == "dev" ]]; then
        xrdcp -C auto --rm-bad-cksum -t 5 adaptyst.sif root://eosuser.cern.ch/$WEB_STORAGE_TMP/apptainer/adaptyst-$CI_COMMIT_SHORT_SHA.sif
      fi
  after_script:
    - rm -f adaptyst.sif
    - kdestroy -A

make-alma10-apptainer-image:
  tags:
    - docker-privileged-xl
  image:
    name: gitlab-registry.cern.ch/linuxsupport/alma10-base
  stage: build
  dependencies: []
  before_script:
    - dnf install -y epel-release
    - dnf install -y apptainer xrootd-client
    - echo $KERBEROS_PASSWORD | kinit ${KERBEROS_USER}
  script:
    - apptainer build --build-arg project_dir="$CI_PROJECT_DIR" adaptyst-alma10.sif $CI_PROJECT_DIR/apptainer-alma.def
    - |
      if [[ "$CI_COMMIT_TAG" != "" ]]; then
        xrdcp -C auto --rm-bad-cksum -t 5 adaptyst-alma10.sif root://eosuser.cern.ch/$WEB_STORAGE/apptainer/adaptyst-alma10-$CI_COMMIT_TAG.sif
      elif [[ "$CI_PIPELINE_SOURCE" == "web" || "$CI_COMMIT_BRANCH" == "dev" ]]; then
        xrdcp -C auto --rm-bad-cksum -t 5 adaptyst-alma10.sif root://eosuser.cern.ch/$WEB_STORAGE_TMP/apptainer/adaptyst-alma10-$CI_COMMIT_SHORT_SHA.sif
      fi
  after_script:
    - rm -f adaptyst-alma10.sif
    - kdestroy -A

doxygen-test:
  image:
    name: registry.cern.ch/docker.io/ubuntu:latest
  stage: test
  dependencies: []
  before_script:
    - apt-get update
    - apt-get install -y doxygen
  script:
    - cd docs
    - doxygen Doxyfile
  artifacts:
    paths:
      - docs/html
    expire_in: 6 h

doxygen-deploy:
  stage: deploy
  dependencies:
    - doxygen-test
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  rules:
    - if: $CI_COMMIT_TAG != null
  script:
    - mv docs/html public
    - deploy-eos
