# Based on https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
stages:
  - opensycl-build
  - base-build

opensycl-root-llvm:
  image: docker:latest
  stage: opensycl-build
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":root-llvm-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = $tag"
      else
        tag=":root-llvm-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - IMAGE_NAME="opensycl"
    - docker build --pull -t "$IMAGE_NAME${tag}" --build-arg="LLVM_GIT_BRANCH=ROOT-llvm13" .
    - docker push "$IMAGE_NAME${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - OpenSYCL/Dockerfile

opensycl-cling-llvm:
  image: docker:latest
  stage: opensycl-build
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=":cling-llvm-latest"
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = $tag"
      else
        tag=":cling-llvm-$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - IMAGE_NAME="opensycl"
    - docker build --pull -t "$IMAGE_NAME${tag}" --build-arg="LLVM_GIT_BRANCH=cling-llvm13" .
    - docker push "$IMAGE_NAME${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - OpenSYCL/Dockerfile

sycl-root-base:
  image: docker:latest
  stage: base-build
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - IMAGE_NAME="sycl-root-base"
    - docker build --pull -t "$IMAGE_NAME${tag}" .
    - docker push "$IMAGE_NAME${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - SYCL-ROOT/Dockerfile
