stages:
  - start-vm
  - vm-setup
  - test
  - vm-deploy
  - deploy

start-vm:
  tags:
    - gentoo-vm-host
  stage: start-vm
  script:
    - |
      if sudo virsh start gentoo; then
        sudo virsh shutdown gentoo
        sudo virsh event gentoo --event lifecycle
        sudo virsh start gentoo
      fi

vm-setup:
  tags:
    - gentoo-vm
  stage: vm-setup
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_setup.sh

vm-test:
  tags:
    - gentoo-vm
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_test.sh

vm-deploy:
  tags:
    - gentoo-vm
  stage: vm-deploy
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_deploy.sh

make-vm-image:
  tags:
    - gentoo-vm-host
  stage: deploy
  artifacts:
    paths:
      - adaptiveperf.qcow2
  script:
    - |
      if sudo virsh shutdown gentoo; then
        if ! sudo virsh list | grep gentoo; then
          exit 1
        fi
      else
        sudo virsh event gentoo --event lifecycle
      fi
    - TMPDIR=/data/gitlab-runner/tmp virt-sparsify /data/gitlab-runner/gentoo.qcow2 $CI_PROJECT_DIR/adaptiveperf.qcow2