stages:
  - deploy-to-instances

deploy:
  tags:
    - gentoo-profiling
  stage: deploy-to-instances
  script:
    - |
      for i in $CI_PROJECT_DIR/OpenSYCL/*; do
        if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
          sudo cp $i /usr/local/bin/
        else
          sudo cp $i "/usr/local/bin/$(basename $i)-$CI_COMMIT_BRANCH"
        fi
      done
