stages:
  - start-vm
  - vm-setup
  - test
  - vm-deploy
  - deploy
  - container-image-build

# Based on https://gitlab.cern.ch/gitlabci-examples/build_docker_image/-/blob/master/.gitlab-ci.yml
make-docker-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: container-image-build
  needs: []
  script:
    - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        export IMAGE_DESTINATION_NAMED=$CI_REGISTRY/adaptiveperf/adaptiveperf:latest
      else
        export IMAGE_DESTINATION_NAMED=$CI_REGISTRY/adaptiveperf/adaptiveperf:branch-$CI_COMMIT_BRANCH
      fi
      export IMAGE_DESTINATION=$CI_REGISTRY/adaptiveperf/adaptiveperf:commit-$CI_COMMIT_SHORT_SHA
    # Prepare Kaniko configuration file
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_DEPLOY_USER\",\"password\":\"$CI_DEPLOY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # Build and push the image from the Dockerfile at the root of the project.
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_DESTINATION --destination $IMAGE_DESTINATION_NAMED --build-arg "JOBS=12"
    # Print the full registry path of the pushed image
    - echo "Image pushed successfully to ${IMAGE_DESTINATION} and ${IMAGE_DESTINATION_NAMED}"

make-apptainer-image:
  tags:
    - gentoo
  stage: container-image-build
  needs: []
  before_script:
    - echo $KERBEROS_PASSWORD | kinit ${KERBEROS_USER}@CERN.CH
    - echo $CI_DEPLOY_PASSWORD | sudo apptainer registry login --username $CI_DEPLOY_USER --password-stdin docker://$CI_REGISTRY
  script:
    - sudo apptainer build --build-arg project_dir="$CI_PROJECT_DIR" --build-arg registry="$CI_REGISTRY" adaptiveperf.sif $CI_PROJECT_DIR/apptainer.def
    - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        xrdfs root://eosuser.cern.ch mv $WEB_STORAGE/apptainer/adaptiveperf-latest.sif $WEB_STORAGE/apptainer/backup-adaptiveperf-latest.sif || true
        xrdcp -C auto --rm-bad-cksum -t 5 adaptiveperf.sif root://eosuser.cern.ch/$WEB_STORAGE/apptainer/adaptiveperf-latest.sif
      else
        xrdfs root://eosuser.cern.ch mv $WEB_STORAGE/apptainer/adaptiveperf-$CI_COMMIT_BRANCH.sif $WEB_STORAGE/apptainer/backup-adaptiveperf-$CI_COMMIT_BRANCH.sif || true
        xrdcp -C auto --rm-bad-cksum -t 5 adaptiveperf.sif root://eosuser.cern.ch/$WEB_STORAGE/apptainer/adaptiveperf-$CI_COMMIT_BRANCH.sif
      fi
  after_script:
    - rm -f adaptiveperf.sif
    - kdestroy -A
    - sudo apptainer registry logout docker://$CI_REGISTRY

start-vm:
  tags:
    - gentoo-vm-host
  stage: start-vm
  script:
    - |
      if ! sudo virsh start gentoo; then
        sudo virsh shutdown gentoo
        sudo virsh event gentoo --event lifecycle
        sleep 1
        sudo virsh start gentoo
      fi

vm-setup:
  tags:
    - gentoo-vm
  stage: vm-setup
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_setup.sh

vm-test:
  tags:
    - gentoo-vm
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_test.sh

vm-deploy:
  tags:
    - gentoo-vm
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: vm-deploy
  script:
    - cd $CI_PROJECT_DIR
    - bash ci/vm_deploy.sh

shutdown-vm:
  tags:
    - gentoo-vm-host
  stage: deploy
  script:
    - |
      if ! sudo virsh shutdown gentoo; then
        if sudo virsh list | grep gentoo; then
          exit 1
        fi
      else
        sudo virsh event gentoo --event lifecycle
      fi

make-vm-image:
  tags:
    - gentoo-vm-host
  stage: deploy
  needs: ["shutdown-vm"]
  before_script:
    - echo $KERBEROS_PASSWORD | kinit ${KERBEROS_USER}@CERN.CH
  script:
    - TMPDIR=/data/gitlab-runner/tmp virt-sparsify --compress /data/gitlab-runner/gentoo.qcow2 $CI_PROJECT_DIR/adaptiveperf.qcow2
    - guestmount -a $CI_PROJECT_DIR/adaptiveperf.qcow2 -m /dev/sda2 /data/gitlab-runner/mnt
    - rm -rf /data/gitlab-runner/mnt/etc/gitlab-runner/config.toml /data/gitlab-runner/mnt/opt/gitlab-runner/* /data/gitlab-runner/mnt/home/profiling/.bash_history && echo "gentoo-adaptiveperf-vm" > /data/gitlab-runner/mnt/etc/hostname
    - guestunmount /data/gitlab-runner/mnt
    - |
      if [[ $CI_COMMIT_BRANCH == "main" ]]; then
        xrdfs root://eosuser.cern.ch mv $WEB_STORAGE/vm/adaptiveperf-latest.qcow2 $WEB_STORAGE/vm/backup-adaptiveperf-latest.qcow2 || true
        xrdcp -C auto --rm-bad-cksum -t 5 $CI_PROJECT_DIR/adaptiveperf.qcow2 root://eosuser.cern.ch/$WEB_STORAGE/vm/adaptiveperf-latest.qcow2
      else
        xrdfs root://eosuser.cern.ch mv $WEB_STORAGE/vm/adaptiveperf-$CI_COMMIT_BRANCH.qcow2 $WEB_STORAGE/vm/backup-adaptiveperf-$CI_COMMIT_BRANCH.qcow2 || true
        xrdcp -C auto --rm-bad-cksum -t 5 $CI_PROJECT_DIR/adaptiveperf.qcow2 root://eosuser.cern.ch/$WEB_STORAGE/vm/adaptiveperf-$CI_COMMIT_BRANCH.qcow2
      fi
  after_script:
    - kdestroy -A

deploy-to-syclops-gentoo-profiling:
  tags:
    - gentoo-profiling
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd $CI_PROJECT_DIR
    - ./build.sh
    - echo | sudo ./install.sh
    - sudo setcap cap_perfmon,cap_bpf+ep /opt/adaptiveperf/perf/bin/perf
  after_script:
    - sudo rm -rf $CI_PROJECT_DIR/linux
