#!/bin/env python3
import re
import sys
from pathlib import Path
from collections import defaultdict

if __name__ == '__main__':
    d = defaultdict(lambda: 0)

    def process(line):
        line = line.strip()

        if len(line) == 0:
            return

        match = re.search(r'^(.+) ([\d\.]+)$', line)

        if match is None:
            raise RuntimeError(line)

        d[match.group(1)] += float(match.group(2))

    for s in sys.argv[2:]:
        p = Path(s)
        with p.open(mode='r') as f:
            for line in f:
                process(line)

    for k, v in d.items():
        print(f'{k} {v}')
