#!/bin/env python3
import re
import sys

if __name__ == "__main__":
   lines = []
   with open(sys.argv[1], mode='r') as f:
      for line in f:
         lines.append(line.strip())

   addrs = set(re.findall(r'\((0x[0-9a-f]+)', '\n'.join(lines)))
   print('\n'.join(addrs))
