#!/bin/bash
IFS=$'\n'

addrs=$(./get_addr $1)
exec=$2
core_file=$3

syms=$((for i in $addrs; do echo info sym $i; done) | gdb $exec $core_file | grep ^"(gdb)" | head -n -1 | ./get_name)

addr_list=()
sym_list=()

for addr in $addrs; do
    addr_list+=($addr)
done

for sym in $syms; do
    sym_list+=($sym)
done

(for ((i=0;i<${#sym_list[@]};i++)); do echo "${addr_list[$i]} ${sym_list[$i]}"; done) | ./replace_addr $1 $5 $6 > $4
