#!/bin/bash
set -e

TO_PROFILE=$(realpath $1)

function convert_from_ns_to_us() {
    while read -ra arr; do
	new_val=$(perl <<< "print ${arr[-1]}/1000")
	arr[-1]=$new_val
	echo ${arr[@]}
    done
}

function perf_record() {
    mkdir results/out
    RESULT_OUT=$(pwd)/results/out
    OLD_DIR=$(pwd)

    cd $(dirname $TO_PROFILE)
    declare -px > dump.env

    # stdout and stderr redirection based on https://unix.stackexchange.com/a/6431
    (sudo perf record --call-graph fp -e task-clock -e syscalls:sys_exit_clone,syscalls:sys_exit_clone3,syscalls:sys_exit_fork,syscalls:sys_exit_vfork -o $RESULT_OUT/perf.data -F $1 --off-cpu -- runuser -u $(whoami) -- /bin/bash -c "source dump.env && $TO_PROFILE" | tee $RESULT_OUT/stdout.log) 3>&1 1>&2 2>&3 | tee $RESULT_OUT/stderr.log

    rm dump.env

    sudo chown $(whoami) $RESULT_OUT/perf.data
    cd $OLD_DIR

    echo "==> Code execution completed!"
}

if ! grep -qs '/sys/kernel/debug ' /proc/mounts; then
    echo "==> /sys/kernel/debug is not mounted, mounting..."
    sudo mount -t debugfs none /sys/kernel/debug
fi

echo "==> Preparing results directory..."
rm -rf results
mkdir results

echo "==> Executing the code..."
perf_record $3

echo "==> Cleaning up and creating collapsed reports..."
cd results
mv out/perf.data .

JOBS=$2
perf script -i perf.data -F comm,tid,pid,time,event,ip,sym,dso,period --no-demangle --max-stack=$(sysctl -n kernel.perf_event_max_stack) --per-event-dump

cat perf.data.task-clock.dump perf.data.offcpu-time.dump | c++filt -p | split_report $JOBS
rm *.dump

PIDS=()
for i in $(seq 0 $((JOBS-1))); do
   script_i="script${i}.data"
   echo -n "Starting $script_i..."
   cat $script_i | stackcollapse-perf.pl --tid | convert_from_ns_to_us > ${script_i:0:-5}_collapsed.data && rm $script_i && echo "$script_i done!" &
   PIDS+=($!)
   echo "PID ${PIDS[-1]}"
done

for pid in ${PIDS[@]}; do
   wait $pid
done

merge script*_collapsed.data > script_collapsed.data.tmp
rm script*_collapsed.data
mv script_collapsed.data.tmp script_collapsed.data

echo "==> Splitting reports into processes/threads..."
cd ..
split_ids results/script_collapsed.data

echo "==> Removing leftover files and producing flame graphs..."
rm results/script*.data
cd results/processed

for i in *.data; do
    flamegraph.pl --countname=us "$i" > "${i:0:-5}.svg"
done

echo "==> All finished! You can check the results directory now."
