#!/bin/bash
syscall_list="syscalls:sys_exit_execve,syscalls:sys_exit_clone,syscalls:sys_enter_exit,syscalls:sys_enter_exit_group,syscalls:sys_enter_clone"
perf_list=$(perf list)

if [[ $(grep syscalls:sys_exit_clone3 <<< "$perf_list" | wc -l) -gt 0 ]]; then
    syscall_list+=",syscalls:sys_exit_clone3"
fi

if [[ $(grep syscalls:sys_exit_fork <<< "$perf_list" | wc -l) -gt 0 ]]; then
    syscall_list+=",syscalls:sys_exit_fork"
fi

if [[ $(grep syscalls:sys_exit_vfork <<< "$perf_list" | wc -l) -gt 0 ]]; then
    syscall_list+=",syscalls:sys_exit_vfork"
fi

if [[ $(grep syscalls:sys_enter_clone3 <<< "$perf_list" | wc -l) -gt 0 ]]; then
    syscall_list+=",syscalls:sys_enter_clone3"
fi

perf record --call-graph fp -k CLOCK_MONOTONIC --buffer-events 1 -e $syscall_list --sorted-stream $@
