#!/bin/bash
# description: AdaptivePerf syscall processing
perf script -s "$PERF_EXEC_PATH"/scripts/python/adaptiveperf-syscall-process.py --demangle --demangle-kernel --max-stack=$(sysctl -n kernel.perf_event_max_stack)
