#!/bin/bash

if [[ $2 == "kernel.perf_event_paranoid" ]]; then
    echo 0
elif [[ $2 == "kernel.perf_event_max_stack" ]]; then
    echo 1024
elif [[ $2 == "kernel.numa_balancing" ]]; then
    echo 0
fi
