#!/bin/env python3
import sys
import re
import math


if __name__ == '__main__':
    parts = int(sys.argv[1])

    blocks = []

    lines = []
    empty = False
    for line in sys.stdin:
        orig_line = line
        line = line.replace('\n', '')

        if len(line) == 0:
            lines.append(orig_line)
            empty = True
        elif empty:
            blocks.append(lines)
            lines = [orig_line]
            empty = False
        else:
            lines.append(orig_line)
            empty = False

    if len(lines) > 0:
        blocks.append(lines)

    block_cnt = math.ceil(len(blocks) / parts)

    index = 0
    for i in range(parts):
        with open(f'script{i}.data', mode='w') as f:
            for j in range(block_cnt):
                if index >= len(blocks):
                    break

                f.write(''.join(blocks[index]))
                index += 1
