#!/bin/env python3
import re
import sys
from pathlib import Path
from collections import defaultdict

if __name__ == '__main__':
    d = []
    overall_offcpu_d = defaultdict(lambda: 0)

    def process(line):
        line = line.strip()

        if len(line) == 0:
            return

        if line[-1] == '#':
            line = line[:-1]
            offcpu = True
        else:
            offcpu = False

        match = re.search(r'^(.+) ([\d\.]+)$', line)

        if match is None:
            raise RuntimeError(line)

        if offcpu:
            overall_offcpu_d[match.group(1)] += float(match.group(2))
        elif len(d) == 0 or d[-1][0] != match.group(1):
            d.append([match.group(1), float(match.group(2))])
        else:
            d[-1][1] += float(match.group(2))

    for s in sys.argv[1:]:
        p = Path(s)
        with p.open(mode='r') as f:
            for line in f:
                process(line)

    def check_k(k):
        parts = k.split(';')

        if len(parts) == 1 and parts[0].startswith('[cold]_'):
            return f'{k[7:]};[cold]_(just thread/process)'

        return k

    with open('overall_offcpu_collapsed.data', mode='w') as f:
        for k, v in overall_offcpu_d.items():
            f.write(f'{check_k(k)} {v}\n')

    for k, v in d:
        print(f'{check_k(k)} {v}')
